# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import simple_example_pb2 as simple__example__pb2


class ShoppingListStub(object):
    """Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OrderGroceries = channel.unary_unary(
                '/shopping.ShoppingList/OrderGroceries',
                request_serializer=simple__example__pb2.MessageRequest.SerializeToString,
                response_deserializer=simple__example__pb2.MessageReply.FromString,
                )


class ShoppingListServicer(object):
    """Service Definition
    """

    def OrderGroceries(self, request, context):
        """Sends grocery order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShoppingListServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OrderGroceries': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderGroceries,
                    request_deserializer=simple__example__pb2.MessageRequest.FromString,
                    response_serializer=simple__example__pb2.MessageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shopping.ShoppingList', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShoppingList(object):
    """Service Definition
    """

    @staticmethod
    def OrderGroceries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopping.ShoppingList/OrderGroceries',
            simple__example__pb2.MessageRequest.SerializeToString,
            simple__example__pb2.MessageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
